[project]
name = "log-files-handler"
version = "0.1.0"
description = "Log files handler"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asciinema>=2.4.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "tabulate>=0.9.0",
]
